version: "3"

services:
  db:
    container_name: "db"
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=questions
    ports:
      - "5432:5432"
    networks:
      - custom
    volumes:
      - pg_data:/var/lib/postgresql/data
  app:
    container_name: app
    image: bee_ai
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:postgres@localhost:5432/questions"
      APP_PORT: "8000"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - custom

networks:
  custom:
    driver: bridge

volumes:
  pg_data:
