version: "3"

services:
  db:
    container_name: "db"
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=questions
    ports:
      - "5432:5432"
    networks:
      - custom

networks:
  custom:
    driver: bridge
