name: Main CI

on: [push]

jobs:
  run_tests:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ vars.DATABASE_URL }}

    steps:
      - user: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11.6

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Install poetry
        run: |
          pip install poetry

      - name: Install project
        run: |
          poetry install

      - name: Run tests
        run: |
          poetry run coverage run -m pytest .
